public sealed record CartItemDto(
    Guid Id,
    Guid HotelId,
    string HotelName,
    Guid HotelRoomTypeId,
    string RoomTypeName,
    short MaxOccupancy,
    int Adults,
    int Children,
    decimal PricePerNight,
    DateOnly CheckIn,
    DateOnly CheckOut,
    int Nights,
    int Quantity,
    decimal Subtotal);