using HotelBooking.Contracts.Search;
using HotelBooking.Domain.Common.Results;

namespace HotelBooking.Application.Common.Interfaces;

/// <summary>
/// Abstraction for hotel search operations (Elasticsearch-backed).
/// </summary>
public interface IHotelSearchService
{
    /// <summary>
    /// Hybrid search: combines BM25 text search + kNN semantic search via RRF.
    /// Falls back to text-only if embeddings are unavailable.
    /// </summary>
    Task<Result<SearchHotelsResponse>> SearchAsync(HotelSearchRequest request, CancellationToken ct);

    /// <summary>
    /// Index or update a single hotel document.
    /// </summary>
    Task IndexHotelAsync(HotelSearchDocument document, CancellationToken ct);

    /// <summary>
    /// Bulk index multiple hotel documents.
    /// </summary>
    Task BulkIndexAsync(IReadOnlyCollection<HotelSearchDocument> documents, CancellationToken ct);

    /// <summary>
    /// Remove a hotel from the search index.
    /// </summary>
    Task RemoveHotelAsync(Guid hotelId, CancellationToken ct);

    /// <summary>
    /// Check if Elasticsearch is available and the index exists.
    /// </summary>
    Task<bool> IsAvailableAsync(CancellationToken ct);
}

/// <summary>
/// Search request DTO passed to the search service.
/// Mirrors the query parameters from SearchHotelsQuery.
/// </summary>
public sealed record HotelSearchRequest(
    string? Query,
    string? City,
    Guid? RoomTypeId,
    DateOnly? CheckIn,
    DateOnly? CheckOut,
    int? Adults,
    int? Children,
    int? NumberOfRooms,
    decimal? MinPrice,
    decimal? MaxPrice,
    short? MinStarRating,
    IReadOnlyCollection<string>? Amenities,
    string? SortBy,
    string? Cursor,
    int Limit = 20);

/// <summary>
/// Document model representing a hotel in the search index.
/// </summary>
public sealed record HotelSearchDocument
{
    public Guid Id { get; init; }
    public string Name { get; init; } = null!;
    public string CityName { get; init; } = null!;
    public string Country { get; init; } = null!;
    public Guid CityId { get; init; }
    public string? Description { get; init; }
    public string Owner { get; init; } = null!;
    public short StarRating { get; init; }
    public decimal? MinPricePerNight { get; init; }
    public double AverageRating { get; init; }
    public int ReviewCount { get; init; }
    public string? ThumbnailUrl { get; init; }
    public List<string> Amenities { get; init; } = [];
    public List<RoomTypeInfo> RoomTypes { get; init; } = [];

    /// <summary>
    /// Combined text for semantic embedding: Name + City + Description + Amenities
    /// </summary>
    public string? SearchableText { get; init; }

    /// <summary>
    /// Dense vector embedding for semantic search (generated by IEmbeddingService).
    /// </summary>
    public float[]? Embedding { get; init; }
}

public sealed record RoomTypeInfo(
    Guid RoomTypeId,
    string RoomTypeName,
    decimal PricePerNight,
    short AdultCapacity,
    short ChildCapacity,
    int AvailableRoomCount);